name: Check Completeness

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
    
    - name: clean
      run: rm -rf *.gcda test_receiver ./receiver/receiver
      
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o  testchecker test_sender.cpp ./sender/*.c
      
    - name: run
      run: ./testchecker
    
    - name: build receiver
      run: g++ -Wall -Wextra -fprofile-arcs ./receiver/receiver.c ./receiver/processingSenderData.c -o ./receiver/receiver 
      
    - name: run receiver
      run: ./receiver/receiver
    
    - name: build test
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage test_receiver.cpp ./receiver/processingSenderData.c -o test_receiver
      
    - name: run test
      run: ./test_receiver

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 21
