name: Receiver Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
         
    - name: build test_receiver
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage test_receiver.cpp ./receiver/processingSenderData.c -o test_receiver
      
    - name: run test_receiver
      run: ./test_receiver
     
    - name: receiver coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o receiver_coverage.html --print-summary

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage_receiver
        path: ./*.html
        retention-days: 21
