name: Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
         
    - name: build sender
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o  testchecker test_sender.cpp ./sender/*.c
      
    - name: sender coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o sender_coverage.html --print-summary
 
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage_sender
        path: ./*.html
        retention-days: 21
